version: '3.5'

networks:
  frontnet:
  backnet:

services:
  frontend:
    build: ./frontend
    container_name: frontend1
    networks:
      - frontnet
    ports:
      - "8000:8000"
    environment:
      - NAME=frontend_container
      - ENDPOINT=http://localhost:9000
    volumes:
      - ./frontend:/opt/frontend


  backend:
    build: ./backend
    container_name: backend
    networks:
      - backnet
    environment:
      - MAP_ENDPOINT=http://api.openweathermap.org/data/2.5
      - APPID=${YOUR_APPID}
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/opt/backend
